# PROYECTO ETL

---

In [1]:
import requests as requests  # alias es cosa mia
import pandas as pd
import json

----

## API pruebas

In [2]:
'''

url = "https://airbnb19.p.rapidapi.com/api/v1/searchProperty"

querystring = {"category":"TAB_8225","totalRecords":"10","currency":"EUR","adults":"1"}

headers = {
	"X-RapidAPI-Key": "eaf5c1a7b2msh5ef97768e954998p145805jsnae2538379312",
	"X-RapidAPI-Host": "airbnb19.p.rapidapi.com"
}

response = requests.request("GET", url, headers=headers, params=querystring)

print(response.text) '''

'\n\nurl = "https://airbnb19.p.rapidapi.com/api/v1/searchProperty"\n\nquerystring = {"category":"TAB_8225","totalRecords":"10","currency":"EUR","adults":"1"}\n\nheaders = {\n\t"X-RapidAPI-Key": "eaf5c1a7b2msh5ef97768e954998p145805jsnae2538379312",\n\t"X-RapidAPI-Host": "airbnb19.p.rapidapi.com"\n}\n\nresponse = requests.request("GET", url, headers=headers, params=querystring)\n\nprint(response.text) '

In [3]:
'''pd.DataFrame(response)'''

'pd.DataFrame(response)'

In [4]:
'''
url = "https://airbnb19.p.rapidapi.com/api/v1/searchDestination"

querystring = {"query":"Palma de Mallorca","country":"Spain"}

headers = {
	"X-RapidAPI-Key": "eaf5c1a7b2msh5ef97768e954998p145805jsnae2538379312",
	"X-RapidAPI-Host": "airbnb19.p.rapidapi.com"
}

response_places = requests.request("GET", url, headers=headers, params=querystring)

print(response_places.text)  '''

'\nurl = "https://airbnb19.p.rapidapi.com/api/v1/searchDestination"\n\nquerystring = {"query":"Palma de Mallorca","country":"Spain"}\n\nheaders = {\n\t"X-RapidAPI-Key": "eaf5c1a7b2msh5ef97768e954998p145805jsnae2538379312",\n\t"X-RapidAPI-Host": "airbnb19.p.rapidapi.com"\n}\n\nresponse_places = requests.request("GET", url, headers=headers, params=querystring)\n\nprint(response_places.text)  '

In [5]:
''' response_places.json().keys()


res_iss.json() '''

' response_places.json().keys()\n\n\nres_iss.json() '

In [6]:
''' response.json().keys()'''

' response.json().keys()'

In [7]:
## %pip install geojson

-----

## INSIDE AIRBN&B web

----

### GEO data de los Municipios

-----

--- he abierto un doc para ver la geo localizacion de los municipios -investigacion del doc-

In [8]:
data = pd.read_json('../w4-ETL-Project/docs/neighbourhoods.geojson')

In [9]:
 '''geo=pd.json_normalize(data.features, max_level=None)
 
geo.head() '''

'geo=pd.json_normalize(data.features, max_level=None)\n\ngeo.head() '

In [10]:
''' geo.to_csv(r'../w4-ETL-Project/data/geo_coordinates_neigbour', index = False) '''

" geo.to_csv(r'../w4-ETL-Project/data/geo_coordinates_neigbour', index = False) "

-----

### Limpiamos Tablas - son unas 4 - revisamos si tienen el mismo orden etc, duplicados...

In [11]:
# MARZON AIRBnB
df_marzo = pd.read_csv('../w4-ETL-Project/docs/listngs_marzo_2022.csv')

df_marzo.head()

,id,listing_url,scrape_id,last_scraped,name,description,neighborhood_overview,picture_url,host_id,host_url,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,11547,https://www.airbnb.com/rooms/11547,20220314155457,2022-03-14,My home at the beach,"Sun, joy, relax, quality, beach & peace.<br />...",NaN,https://a0.muscache.com/pictures/494126/8c151b...,42942,https://www.airbnb.com/users/show/42942,...,4.93,4.79,4.77,NaN,f,1,1,0,0,0.87
1,69998,https://www.airbnb.com/rooms/69998,20220314155457,2022-03-15,COZY HIDEAWAY LOFT... MI AMOR...,Perfect place to escape for a few days of peac...,( soho-chic bohemian neighborhood of the city ...,https://a0.muscache.com/pictures/6d4007c1-f223...,353156,https://www.airbnb.com/users/show/353156,...,4.95,4.86,4.77,NaN,f,2,2,0,0,1.60
2,100831,https://www.airbnb.com/rooms/100831,20220314155457,2022-03-15,HOUSE IN MALLORCA - WiFi(ET-3045),<b>The space</b><br />House situated in a quie...,NaN,https://a0.muscache.com/pictures/675527/72b329...,529151,https://www.airbnb.com/users/show/529151,...,4.90,4.71,4.86,ETV-3045,f,1,1,0,0,0.16
3,105891,https://www.airbnb.com/rooms/105891,20220314155457,2022-03-14,VILLAGE HOUSE WITH POOL: IDEAL FOR FAMILIES,The house is equipped with the furniture and e...,The village's population does not reach two th...,https://a0.muscache.com/pictures/1036816/f36ce...,549192,https://www.airbnb.com/users/show/549192,...,4.93,4.71,4.93,ETV/6127,f,1,1,0,0,0.13
4,106833,https://www.airbnb.com/rooms/106833,20220314155457,2022-03-14,Villa with a big pool in Mallorca,<b>The space</b><br />This is a restored old b...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,551974,https://www.airbnb.com/users/show/551974,...,5.00,4.44,4.56,ET/1961,f,1,1,0,0,0.08

In [12]:
df_marzo.info('deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17795 entries, 0 to 17794
Data columns (total 74 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            17795 non-null  int64
 1   listing_url                                   17795 non-null  object
 2   scrape_id                                     17795 non-null  int64
 3   last_scraped                                  17795 non-null  object
 4   name                                          17794 non-null  object
 5   description                                   17557 non-null  object
 6   neighborhood_overview                         7387 non-null   object
 7   picture_url                                   17795 non-null  object
 8   host_id                                       17795 non-null  int64
 9   host_url                                      17795 non-null  object
 10  host_name                                     17751 non-null  object
 11  host_since                                    17751 non-null  object
 12  host_location                                 17729 non-null  object
 13  host_about                                    11452 non-null  object
 14  host_response_time                            16160 non-null  object
 15  host_response_rate                            16160 non-null  object
 16  host_acceptance_rate                          16639 non-null  object
 17  host_is_superhost                             17751 non-null  object
 18  host_thumbnail_url                            17751 non-null  object
 19  host_picture_url                              17751 non-null  object
 20  host_neighbourhood                            2436 non-null   object
 21  host_listings_count                           17751 non-null  float64
 22  host_total_listings_count                     17751 non-null  float64
 23  host_verifications                            17795 non-null  object
 24  host_has_profile_pic                          17751 non-null  object
 25  host_identity_verified                        17751 non-null  object
 26  neighbourhood                                 7387 non-null   object
 27  neighbourhood_cleansed                        17795 non-null  object
 28  neighbourhood_group_cleansed                  0 non-null      float64
 29  latitude                                      17795 non-null  float64
 30  longitude                                     17795 non-null  float64
 31  property_type                                 17795 non-null  object
 32  room_type                                     17795 non-null  object
 33  accommodates                                  17795 non-null  int64
 34  bathrooms                                     0 non-null      float64
 35  bathrooms_text                                17767 non-null  object
 36  bedrooms                                      17540 non-null  float64
 37  beds                                          17634 non-null  float64
 38  amenities                                     17795 non-null  object
 39  price                                         17795 non-null  object
 40  minimum_nights                                17795 non-null  int64
 41  maximum_nights                                17795 non-null  int64
 42  minimum_minimum_nights                        17794 non-null  float64
 43  maximum_minimum_nights                        17794 non-null  float64
 44  minimum_maximum_nights                        17794 non-null  float64
 45  maximum_maximum_nights                        17794 non-null  float64
 46  minimum_nights_avg_ntm                        17794 non-null  float64
 47  maximum_nights_avg_ntm                        17794 non-null  float64
 48  calendar_updated                              0 non-null      float64
 49  has_availability                              17795 non-null  object
 50  availability_30                               17795 non-null  int64
 51  availability_60                               17795 non-null  int64
 52  availability_90                               17795 non-null  int64
 53  availability_365                              17795 non-null  int64
 54  calendar_last_scraped                         17795 non-null  object
 55  number_of_reviews                             17795 non-null  int64
 56  number_of_reviews_ltm                         17795 non-null  int64
 57  number_of_reviews_l30d                        17795 non-null  int64
 58  first_review                                  11920 non-null  object
 59  last_review                                   11920 non-null  object
 60  review_scores_rating                          11920 non-null  float64
 61  review_scores_accuracy                        11810 non-null  float64
 62  review_scores_cleanliness                     11810 non-null  float64
 63  review_scores_checkin                         11807 non-null  float64
 64  review_scores_communication                   11809 non-null  float64
 65  review_scores_location                        11806 non-null  float64
 66  review_scores_value                           11806 non-null  float64
 67  license                                       10989 non-null  object
 68  instant_bookable                              17795 non-null  object
 69  calculated_host_listings_count                17795 non-null  int64
 70  calculated_host_listings_count_entire_homes   17795 non-null  int64
 71  calculated_host_listings_count_private_rooms  17795 non-null  int64
 72  calculated_host_listings_count_shared_rooms   17795 non-null  int64
 73  reviews_per_month                             11920 non-null  float64
dtypes: float64(23), int64(17), object(34)
memory usage: 10.0+ MB

In [13]:
df_marzo.shape

(17795, 74)

In [14]:
df_junio = pd.read_csv('../w4-ETL-Project/docs/listings_june_2022.csv')

df_junio.head()

,id,listing_url,scrape_id,last_scraped,name,description,neighborhood_overview,picture_url,host_id,host_url,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,33442954,https://www.airbnb.com/rooms/33442954,20220610041431,2022-06-10,"Air-Conditioned Apartment with Wi-Fi, Balcony ...","In Port de Sóller, directly at the sea, the ap...",NaN,https://a0.muscache.com/pictures/prohost-api/H...,205499549,https://www.airbnb.com/users/show/205499549,...,4.93,5.00,4.40,NaN,t,135,135,0,0,0.40
1,46137925,https://www.airbnb.com/rooms/46137925,20220610041431,2022-06-10,TONY 1A,We are delighted to offer you this three-bedro...,NaN,https://a0.muscache.com/pictures/7a32d936-ee8b...,313785862,https://www.airbnb.com/users/show/313785862,...,4.83,5.00,4.67,VTV0751 BAL,t,127,127,0,0,0.57
2,53146067,https://www.airbnb.com/rooms/53146067,20220610041431,2022-06-10,Ca na JB,Este alojamiento tiene una ubicación estratégi...,NaN,https://a0.muscache.com/pictures/a4b789a8-e332...,247923097,https://www.airbnb.com/users/show/247923097,...,NaN,NaN,NaN,NaN,t,1,1,0,0,NaN
3,49646764,https://www.airbnb.com/rooms/49646764,20220610041431,2022-06-10,Apartamento Bona Vista,Precioso y acogedor apartamento con una gran t...,NaN,https://a0.muscache.com/pictures/724cf1af-350b...,135102157,https://www.airbnb.com/users/show/135102157,...,5.00,5.00,5.00,NaN,t,1,1,0,0,0.58
4,30172628,https://www.airbnb.com/rooms/30172628,20220610041431,2022-06-10,Beachfront Villa Socias Playa,"IMPORTANT: In response to COVID-19, this prope...",NaN,https://a0.muscache.com/pictures/7079fb70-0519...,122491844,https://www.airbnb.com/users/show/122491844,...,4.00,4.75,4.50,L12E8492,t,189,189,0,0,0.10

In [15]:
df_junio.shape

(18298, 74)

In [16]:
# tengo 4 tablas, mismas columnas gracias Dios; 2 de 2022 y 2 de 2021, mismas columnas, las concatenamos para crear una tabl total
# De esta forma tenemos un max de listings de airbnb que me da la web
# Mas representativo al sacar medias de precios durante todo el año para hacer las comparaciones
# Mas facil de limpiar.

In [17]:
df_marzo22 = pd.read_csv('../w4-ETL-Project/docs/listngs_marzo_2022.csv')
df_jun22 = pd.read_csv('../w4-ETL-Project/docs/listings_june_2022.csv')
df_sept21 = pd.read_csv('../w4-ETL-Project/docs/listings_sept_2021.csv')
df_dec21 =pd.read_csv('../w4-ETL-Project/docs/listings_dec_2021.csv')
df_all_rows = pd.concat([df_marzo22, df_jun22, df_sept21, df_dec21], axis = 0)
df_all_rows.head()

,id,listing_url,scrape_id,last_scraped,name,description,neighborhood_overview,picture_url,host_id,host_url,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,11547,https://www.airbnb.com/rooms/11547,20220314155457,2022-03-14,My home at the beach,"Sun, joy, relax, quality, beach & peace.<br />...",NaN,https://a0.muscache.com/pictures/494126/8c151b...,42942,https://www.airbnb.com/users/show/42942,...,4.93,4.79,4.77,NaN,f,1,1,0,0,0.87
1,69998,https://www.airbnb.com/rooms/69998,20220314155457,2022-03-15,COZY HIDEAWAY LOFT... MI AMOR...,Perfect place to escape for a few days of peac...,( soho-chic bohemian neighborhood of the city ...,https://a0.muscache.com/pictures/6d4007c1-f223...,353156,https://www.airbnb.com/users/show/353156,...,4.95,4.86,4.77,NaN,f,2,2,0,0,1.60
2,100831,https://www.airbnb.com/rooms/100831,20220314155457,2022-03-15,HOUSE IN MALLORCA - WiFi(ET-3045),<b>The space</b><br />House situated in a quie...,NaN,https://a0.muscache.com/pictures/675527/72b329...,529151,https://www.airbnb.com/users/show/529151,...,4.90,4.71,4.86,ETV-3045,f,1,1,0,0,0.16
3,105891,https://www.airbnb.com/rooms/105891,20220314155457,2022-03-14,VILLAGE HOUSE WITH POOL: IDEAL FOR FAMILIES,The house is equipped with the furniture and e...,The village's population does not reach two th...,https://a0.muscache.com/pictures/1036816/f36ce...,549192,https://www.airbnb.com/users/show/549192,...,4.93,4.71,4.93,ETV/6127,f,1,1,0,0,0.13
4,106833,https://www.airbnb.com/rooms/106833,20220314155457,2022-03-14,Villa with a big pool in Mallorca,<b>The space</b><br />This is a restored old b...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,551974,https://www.airbnb.com/users/show/551974,...,5.00,4.44,4.56,ET/1961,f,1,1,0,0,0.08

In [18]:
df_all_rows.shape

(72035, 74)

In [19]:
df_all_rows.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'name', 'description',
       'neighborhood_overview', 'picture_url', 'host_id', 'host_url',
       'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'first_review',
       'last_review', 'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object')

In [20]:
# Voy a dropear columnas no necesarias, aunque dejo algunas extras por si aca.

In [21]:
df_rmv_columns= df_all_rows.drop(['neighborhood_overview','picture_url','host_about','host_response_time','host_response_rate','host_thumbnail_url','host_picture_url','host_neighbourhood','host_listings_count','host_listings_count','host_has_profile_pic','neighbourhood_group_cleansed','bathrooms','amenities','calendar_updated','calculated_host_listings_count_private_rooms','calculated_host_listings_count_shared_rooms'], axis=1)


df_rmv_columns.shape

(72035, 58)

In [22]:
#confirmo que las que quedan de columnas están bien
df_rmv_columns.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'name', 'description',
       'host_id', 'host_url', 'host_name', 'host_since', 'host_location',
       'host_acceptance_rate', 'host_is_superhost',
       'host_total_listings_count', 'host_verifications',
       'host_identity_verified', 'neighbourhood', 'neighbourhood_cleansed',
       'latitude', 'longitude', 'property_type', 'room_type', 'accommodates',
       'bathrooms_text', 'bedrooms', 'beds', 'price', 'minimum_nights',
       'maximum_nights', 'minimum_minimum_nights', 'maximum_minimum_nights',
       'minimum_maximum_nights', 'maximum_maximum_nights',
       'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'first_review',
       'last_review', 'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes', 'reviews_per_month'],
      dtype='object')

In [23]:
df_rmv_columns.drop_duplicates(inplace=True)

In [24]:
#no hay duplicados, entiendo que no se repiten ids ni nada, porque al coger fechas diferentes en el scrapeo no tiene porque coincidir
df_rmv_columns.shape

(72035, 58)

### Empezamos a ver que columnas nuevas necesitammos

---

In [25]:
# En primer lugar no deberia haber muchos nulos al haber eliminado columnas con datos vacios, pero si que habra algunos con N/A
# solo hay dos columnas, y no son relevantes por lo que las dejo tal cual.

In [26]:
df_rmv_columns.info('deep')

<class 'pandas.core.frame.DataFrame'>
Int64Index: 72035 entries, 0 to 17632
Data columns (total 58 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   id                                           72035 non-null  int64
 1   listing_url                                  72035 non-null  object
 2   scrape_id                                    72035 non-null  int64
 3   last_scraped                                 72035 non-null  object
 4   name                                         72031 non-null  object
 5   description                                  71103 non-null  object
 6   host_id                                      72035 non-null  int64
 7   host_url                                     72035 non-null  object
 8   host_name                                    71197 non-null  object
 9   host_since                                   71197 non-null  object
 10  host_location                                71104 non-null  object
 11  host_acceptance_rate                         62738 non-null  object
 12  host_is_superhost                            71197 non-null  object
 13  host_total_listings_count                    71197 non-null  float64
 14  host_verifications                           72035 non-null  object
 15  host_identity_verified                       71197 non-null  object
 16  neighbourhood                                30412 non-null  object
 17  neighbourhood_cleansed                       72035 non-null  object
 18  latitude                                     72035 non-null  float64
 19  longitude                                    72035 non-null  float64
 20  property_type                                72035 non-null  object
 21  room_type                                    72035 non-null  object
 22  accommodates                                 72035 non-null  int64
 23  bathrooms_text                               71935 non-null  object
 24  bedrooms                                     71012 non-null  float64
 25  beds                                         71183 non-null  float64
 26  price                                        72035 non-null  object
 27  minimum_nights                               72035 non-null  int64
 28  maximum_nights                               72035 non-null  int64
 29  minimum_minimum_nights                       72032 non-null  float64
 30  maximum_minimum_nights                       72032 non-null  float64
 31  minimum_maximum_nights                       72032 non-null  float64
 32  maximum_maximum_nights                       72032 non-null  float64
 33  minimum_nights_avg_ntm                       72032 non-null  float64
 34  maximum_nights_avg_ntm                       72032 non-null  float64
 35  has_availability                             72035 non-null  object
 36  availability_30                              72035 non-null  int64
 37  availability_60                              72035 non-null  int64
 38  availability_90                              72035 non-null  int64
 39  availability_365                             72035 non-null  int64
 40  calendar_last_scraped                        72035 non-null  object
 41  number_of_reviews                            72035 non-null  int64
 42  number_of_reviews_ltm                        72035 non-null  int64
 43  number_of_reviews_l30d                       72035 non-null  int64
 44  first_review                                 49003 non-null  object
 45  last_review                                  49003 non-null  object
 46  review_scores_rating                         49003 non-null  float64
 47  review_scores_accuracy                       48548 non-null  float64
 48  review_scores_cleanliness                    48549 non-null  float64
 49  review_scores_checkin                        48537 non-null  float64
 50  review_scores_communication                  48546 non-null  float64
 51  review_scores_location                       48533 non-null  float64
 52  review_scores_value                          48533 non-null  float64
 53  license                                      44491 non-null  object
 54  instant_bookable                             72035 non-null  object
 55  calculated_host_listings_count               72035 non-null  int64
 56  calculated_host_listings_count_entire_homes  72035 non-null  int64
 57  reviews_per_month                            49003 non-null  float64
dtypes: float64(19), int64(15), object(24)
memory usage: 32.4+ MB

In [27]:
df_all_rows.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'name', 'description',
       'neighborhood_overview', 'picture_url', 'host_id', 'host_url',
       'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'first_review',
       'last_review', 'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object')

In [28]:
# la idea es sacar una columna que si hay 2 habitaciones diga que son 50m2, sin hay 4 hab. son 100m2 etc.  Asi podre comparar mas adelante
# Otra para calcular el precio x mes x 
df_rmv_columns.head()

,id,listing_url,scrape_id,last_scraped,name,description,host_id,host_url,host_name,host_since,...,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,reviews_per_month
0,11547,https://www.airbnb.com/rooms/11547,20220314155457,2022-03-14,My home at the beach,"Sun, joy, relax, quality, beach & peace.<br />...",42942,https://www.airbnb.com/users/show/42942,Daniel,2009-10-02,...,4.58,4.92,4.93,4.79,4.77,NaN,f,1,1,0.87
1,69998,https://www.airbnb.com/rooms/69998,20220314155457,2022-03-15,COZY HIDEAWAY LOFT... MI AMOR...,Perfect place to escape for a few days of peac...,353156,https://www.airbnb.com/users/show/353156,Lor,2011-01-19,...,4.92,4.94,4.95,4.86,4.77,NaN,f,2,2,1.60
2,100831,https://www.airbnb.com/rooms/100831,20220314155457,2022-03-15,HOUSE IN MALLORCA - WiFi(ET-3045),<b>The space</b><br />House situated in a quie...,529151,https://www.airbnb.com/users/show/529151,Miguel,2011-04-23,...,4.95,5.00,4.90,4.71,4.86,ETV-3045,f,1,1,0.16
3,105891,https://www.airbnb.com/rooms/105891,20220314155457,2022-03-14,VILLAGE HOUSE WITH POOL: IDEAL FOR FAMILIES,The house is equipped with the furniture and e...,549192,https://www.airbnb.com/users/show/549192,Bartomeu,2011-05-01,...,5.00,4.86,4.93,4.71,4.93,ETV/6127,f,1,1,0.13
4,106833,https://www.airbnb.com/rooms/106833,20220314155457,2022-03-14,Villa with a big pool in Mallorca,<b>The space</b><br />This is a restored old b...,551974,https://www.airbnb.com/users/show/551974,Xisco,2011-05-02,...,4.78,4.89,5.00,4.44,4.56,ET/1961,f,1,1,0.08

In [29]:
# vamos a contar el numero de habitaciones como se distribuyen
#pandas.dataframe.column-name.unique()

In [30]:
# muy bienm asi vemos la distribución y podemos  diseñar el loop para la nueva columna

df_rmv_columns.groupby('bedrooms').count()[:15]

,id,listing_url,scrape_id,last_scraped,name,description,host_id,host_url,host_name,host_since,...,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,reviews_per_month
bedrooms,,,,,,,,,,,,,,,,,,,,,
1.0,13704,13704,13704,13704,13704,13276,13704,13704,13638,13638,...,10511,10511,10511,10511,10511,4845,13704,13704,13704,10547
2.0,14234,14234,14234,14234,14230,14103,14234,14234,14096,14096,...,10453,10451,10453,10451,10451,8389,14234,14234,14234,10515
3.0,21827,21827,21827,21827,21827,21746,21827,21827,21518,21518,...,14234,14234,14234,14230,14230,15752,21827,21827,21827,14389
4.0,13276,13276,13276,13276,13276,13165,13276,13276,13067,13067,...,7986,7980,7983,7980,7980,9681,13276,13276,13276,8084
5.0,4847,4847,4847,4847,4847,4805,4847,4847,4774,4774,...,2862,2862,2862,2862,2862,3398,4847,4847,4847,2929
6.0,2353,2353,2353,2353,2353,2315,2353,2353,2319,2319,...,1275,1271,1275,1271,1271,1645,2353,2353,2353,1301
7.0,361,361,361,361,361,357,361,361,353,353,...,211,211,211,211,211,259,361,361,361,215
8.0,243,243,243,243,243,237,243,243,243,243,...,117,117,117,117,117,143,243,243,243,121
9.0,39,39,39,39,39,35,39,39,39,39,...,15,15,15,15,15,12,39,39,39,15
10.0,22,22,22,22,22,22,22,22,21,21,...,11,11,11,11,11,16,22,22,22,11
11.0,6,6,6,6,6,6,6,6,6,6,...,2,2,2,2,2,4,6,6,6,2
12.0,56,56,56,56,56,56,56,56,56,56,...,28,28,28,28,28,21,56,56,56,28
13.0,8,8,8,8,8,8,8,8,8,8,...,3,3,3,3,3,4,8,8,8,3
14.0,8,8,8,8,8,8,8,8,8,8,...,4,4,4,4,4,4,8,8,8,4

In [31]:
#vamos a borrar todas las filas que tiene mas de hasbitaciones, porque al final complica el estudio ya que hay menos y es mas dificil de calcular

In [32]:
'''data_bedrooms = df_rmv_columns.loc[(df_rmv_columns['bedrooms'] > 8)]
data_bedrooms.shape '''

"data_bedrooms = df_rmv_columns.loc[(df_rmv_columns['bedrooms'] > 8)]\ndata_bedrooms.shape "

In [33]:
# parece funcionar, haciendo esta formula

df_rmv_columns.drop(df_rmv_columns[df_rmv_columns.bedrooms > 6].index, inplace=True)
df_rmv_columns.shape

(69014, 58)

In [34]:
#vamos a crear la nueva columna con datos de los rangos en m2 basado en el numero de habitaciones

In [35]:
df = df_rmv_columns

In [36]:
import numpy as np

In [37]:
conditions = [
    (df['bedrooms'] <= 2),
    (df['bedrooms'] == 3),
    (df['bedrooms'] >= 4) & (df['bedrooms'] <= 5),
    (df['bedrooms'] > 5)]

values = ['50', '85', '120', '180']
df['sq_meters'] = np.select(conditions, values)

In [38]:
#ha incluido la nueva columna, con nuestras condiciones ( Impresionante)
df.shape

(69014, 59)

In [39]:
#comprobamos si es correcto y lo es!

df[['bedrooms', 'sq_meters']]

       bedrooms sq_meters
0           1.0        50
1           1.0        50
2           4.0       120
3           3.0        85
4           2.0        50
...         ...       ...
17628       5.0       120
17629       1.0        50
17630       3.0        85
17631       1.0        50
17632       2.0        50

[69014 rows x 2 columns]

In [40]:
# ahora haremos unos nuevos condicionales, ya que tenemos las fechas de cuando se escrapearon los arbnb podemos incluir la media de precios de esos meses que
# provee Idealista

# tengo precio por noche, metros cuadrados, podemos generar nueva columna con el calculo si son un mes x metro cuadrado
# 
#  Luego incluimos precios alguiler de mercado

In [41]:
df.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'name', 'description',
       'host_id', 'host_url', 'host_name', 'host_since', 'host_location',
       'host_acceptance_rate', 'host_is_superhost',
       'host_total_listings_count', 'host_verifications',
       'host_identity_verified', 'neighbourhood', 'neighbourhood_cleansed',
       'latitude', 'longitude', 'property_type', 'room_type', 'accommodates',
       'bathrooms_text', 'bedrooms', 'beds', 'price', 'minimum_nights',
       'maximum_nights', 'minimum_minimum_nights', 'maximum_minimum_nights',
       'minimum_maximum_nights', 'maximum_maximum_nights',
       'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'first_review',
       'last_review', 'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes', 'reviews_per_month',
       'sq_meters'],
      dtype='object')

In [42]:
# vamos a generar la columna nueva , precio arbnb x mes. Multiplicamos el precio x 30 noches
# tenemos el $ en la columna price, hay que eliminarlo y cambiar la columna a integer antes de esta formuala

In [43]:
df.dtypes

id                                               int64
listing_url                                     object
scrape_id                                        int64
last_scraped                                    object
name                                            object
description                                     object
host_id                                          int64
host_url                                        object
host_name                                       object
host_since                                      object
host_location                                   object
host_acceptance_rate                            object
host_is_superhost                               object
host_total_listings_count                      float64
host_verifications                              object
host_identity_verified                          object
neighbourhood                                   object
neighbourhood_cleansed                          object
latitude                                       float64
longitude                                      float64
property_type                                   object
room_type                                       object
accommodates                                     int64
bathrooms_text                                  object
bedrooms                                       float64
beds                                           float64
price                                           object
minimum_nights                                   int64
maximum_nights                                   int64
minimum_minimum_nights                         float64
maximum_minimum_nights                         float64
minimum_maximum_nights                         float64
maximum_maximum_nights                         float64
minimum_nights_avg_ntm                         float64
maximum_nights_avg_ntm                         float64
has_availability                                object
availability_30                                  int64
availability_60                                  int64
availability_90                                  int64
availability_365                                 int64
calendar_last_scraped                           object
number_of_reviews                                int64
number_of_reviews_ltm                            int64
number_of_reviews_l30d                           int64
first_review                                    object
last_review                                     object
review_scores_rating                           float64
review_scores_accuracy                         float64
review_scores_cleanliness                      float64
review_scores_checkin                          float64
review_scores_communication                    float64
review_scores_location                         float64
review_scores_value                            float64
license                                         object
instant_bookable                                object
calculated_host_listings_count                   int64
calculated_host_listings_count_entire_homes      int64
reviews_per_month                              float64
sq_meters                                       object
dtype: object

In [44]:
#here im replacing the $ sign for nothin and also the "," in the thousands which was not letting me to change the column from a string to a float
# this way now i'm able do the next calculations without the error " cant multiply a string vs integer"
df['price'] = df['price'].str.replace('$','')
df['price'] = df['price'].str.replace(',','')
print(df.price)

0         91.00
1         87.00
2        155.00
3        110.00
4        200.00
          ...
17628    398.00
17629     25.00
17630    211.00
17631    195.00
17632     85.00
Name: price, Length: 69014, dtype: object

/var/folders/94/v2x46p016qs_tyhzbgv7ywm40000gn/T/ipykernel_97335/44103457.py:3: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['price'] = df['price'].str.replace('$','')

In [45]:
# downcasting from object string to float the price column

df["price"] = pd.to_numeric(df["price"], downcast="float")

In [46]:
# confirming that has worked
print(df.dtypes)

id                                               int64
listing_url                                     object
scrape_id                                        int64
last_scraped                                    object
name                                            object
description                                     object
host_id                                          int64
host_url                                        object
host_name                                       object
host_since                                      object
host_location                                   object
host_acceptance_rate                            object
host_is_superhost                               object
host_total_listings_count                      float64
host_verifications                              object
host_identity_verified                          object
neighbourhood                                   object
neighbourhood_cleansed                          object
latitude                                       float64
longitude                                      float64
property_type                                   object
room_type                                       object
accommodates                                     int64
bathrooms_text                                  object
bedrooms                                       float64
beds                                           float64
price                                          float32
minimum_nights                                   int64
maximum_nights                                   int64
minimum_minimum_nights                         float64
maximum_minimum_nights                         float64
minimum_maximum_nights                         float64
maximum_maximum_nights                         float64
minimum_nights_avg_ntm                         float64
maximum_nights_avg_ntm                         float64
has_availability                                object
availability_30                                  int64
availability_60                                  int64
availability_90                                  int64
availability_365                                 int64
calendar_last_scraped                           object
number_of_reviews                                int64
number_of_reviews_ltm                            int64
number_of_reviews_l30d                           int64
first_review                                    object
last_review                                     object
review_scores_rating                           float64
review_scores_accuracy                         float64
review_scores_cleanliness                      float64
review_scores_checkin                          float64
review_scores_communication                    float64
review_scores_location                         float64
review_scores_value                            float64
license                                         object
instant_bookable                                object
calculated_host_listings_count                   int64
calculated_host_listings_count_entire_homes      int64
reviews_per_month                              float64
sq_meters                                       object
dtype: object

In [47]:
# At first iw as goinggto divide price/ by minimum_nights ( because in some cases, the minmum stay can be 3 days, which will make our data unconsistent) then we multiply by 30 days
# but i double check and always price is per night so no need for the division with the minimun night.
# now lets see if we can do the new column with the calculation and make sure it did work

df['price_monthly'] = (df['price']) * 30
df.head()

,id,listing_url,scrape_id,last_scraped,name,description,host_id,host_url,host_name,host_since,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,reviews_per_month,sq_meters,price_monthly
0,11547,https://www.airbnb.com/rooms/11547,20220314155457,2022-03-14,My home at the beach,"Sun, joy, relax, quality, beach & peace.<br />...",42942,https://www.airbnb.com/users/show/42942,Daniel,2009-10-02,...,4.93,4.79,4.77,NaN,f,1,1,0.87,50,2730.0
1,69998,https://www.airbnb.com/rooms/69998,20220314155457,2022-03-15,COZY HIDEAWAY LOFT... MI AMOR...,Perfect place to escape for a few days of peac...,353156,https://www.airbnb.com/users/show/353156,Lor,2011-01-19,...,4.95,4.86,4.77,NaN,f,2,2,1.60,50,2610.0
2,100831,https://www.airbnb.com/rooms/100831,20220314155457,2022-03-15,HOUSE IN MALLORCA - WiFi(ET-3045),<b>The space</b><br />House situated in a quie...,529151,https://www.airbnb.com/users/show/529151,Miguel,2011-04-23,...,4.90,4.71,4.86,ETV-3045,f,1,1,0.16,120,4650.0
3,105891,https://www.airbnb.com/rooms/105891,20220314155457,2022-03-14,VILLAGE HOUSE WITH POOL: IDEAL FOR FAMILIES,The house is equipped with the furniture and e...,549192,https://www.airbnb.com/users/show/549192,Bartomeu,2011-05-01,...,4.93,4.71,4.93,ETV/6127,f,1,1,0.13,85,3300.0
4,106833,https://www.airbnb.com/rooms/106833,20220314155457,2022-03-14,Villa with a big pool in Mallorca,<b>The space</b><br />This is a restored old b...,551974,https://www.airbnb.com/users/show/551974,Xisco,2011-05-02,...,5.00,4.44,4.56,ET/1961,f,1,1,0.08,50,6000.0

In [48]:
# calculations are fine and consistent

df[['price', 'minimum_nights', 'price_monthly','sq_meters','listing_url']]

,price,minimum_nights,price_monthly,sq_meters,listing_url
0,91.0,7,2730.0,50,https://www.airbnb.com/rooms/11547
1,87.0,3,2610.0,50,https://www.airbnb.com/rooms/69998
2,155.0,7,4650.0,120,https://www.airbnb.com/rooms/100831
3,110.0,6,3300.0,85,https://www.airbnb.com/rooms/105891
4,200.0,5,6000.0,50,https://www.airbnb.com/rooms/106833
...,...,...,...,...,...
17628,398.0,1,11940.0,120,https://www.airbnb.com/rooms/53768559
17629,25.0,1,750.0,50,https://www.airbnb.com/rooms/53770992
17630,211.0,1,6330.0,85,https://www.airbnb.com/rooms/53777865
17631,195.0,1,5850.0,50,https://www.airbnb.com/rooms/53782321
17632,85.0,6,2550.0,50,https://www.airbnb.com/rooms/53791212

In [49]:
df.shape

(69014, 60)

In [50]:
# we need to change the column sqm into a integer befor calculating anything
df["sq_meters"] = pd.to_numeric(df["sq_meters"], downcast="integer")

In [51]:
# alright! now I will just do a new column with the price / sq_meter _ this output will be to match it with other datasources..
# ..that provide the avg price x sqm of rents by Municipios AKA Districts ( based on Montly data)

df['price_sqm_amonth'] = df['price_monthly'] / df['sq_meters']

In [52]:
# looking gorgeous

df[['price', 'minimum_nights', 'price_monthly','sq_meters','listing_url','price_sqm_amonth','last_scraped' ]]

,price,minimum_nights,price_monthly,sq_meters,listing_url,price_sqm_amonth,last_scraped
0,91.0,7,2730.0,50,https://www.airbnb.com/rooms/11547,54.599998,2022-03-14
1,87.0,3,2610.0,50,https://www.airbnb.com/rooms/69998,52.200001,2022-03-15
2,155.0,7,4650.0,120,https://www.airbnb.com/rooms/100831,38.750000,2022-03-15
3,110.0,6,3300.0,85,https://www.airbnb.com/rooms/105891,38.823528,2022-03-14
4,200.0,5,6000.0,50,https://www.airbnb.com/rooms/106833,120.000000,2022-03-14
...,...,...,...,...,...,...,...
17628,398.0,1,11940.0,120,https://www.airbnb.com/rooms/53768559,99.500000,2021-12-13
17629,25.0,1,750.0,50,https://www.airbnb.com/rooms/53770992,15.000000,2021-12-13
17630,211.0,1,6330.0,85,https://www.airbnb.com/rooms/53777865,74.470589,2021-12-13
17631,195.0,1,5850.0,50,https://www.airbnb.com/rooms/53782321,117.000000,2021-12-13
17632,85.0,6,2550.0,50,https://www.airbnb.com/rooms/53791212,51.000000,2021-12-13

In [53]:
# to work in the future with sql we are going to check if the column scrapp data is in a date format 
# will also be necessary to group by  and use conditionals since we also be provinding data based by the months we have
# shows that we have an object so alright! that will work but we will make a little adjustment taking the days out, since are not valuable

# so i went and created new column with year and month only 

df['last_scraped_month'] = pd.to_datetime(df['last_scraped']).dt.strftime('%Y-%m')

In [54]:
df[['price', 'minimum_nights', 'price_monthly','sq_meters','listing_url','price_sqm_amonth','last_scraped', 'last_scraped_month' ]]

,price,minimum_nights,price_monthly,sq_meters,listing_url,price_sqm_amonth,last_scraped,last_scraped_month
0,91.0,7,2730.0,50,https://www.airbnb.com/rooms/11547,54.599998,2022-03-14,2022-03
1,87.0,3,2610.0,50,https://www.airbnb.com/rooms/69998,52.200001,2022-03-15,2022-03
2,155.0,7,4650.0,120,https://www.airbnb.com/rooms/100831,38.750000,2022-03-15,2022-03
3,110.0,6,3300.0,85,https://www.airbnb.com/rooms/105891,38.823528,2022-03-14,2022-03
4,200.0,5,6000.0,50,https://www.airbnb.com/rooms/106833,120.000000,2022-03-14,2022-03
...,...,...,...,...,...,...,...,...
17628,398.0,1,11940.0,120,https://www.airbnb.com/rooms/53768559,99.500000,2021-12-13,2021-12
17629,25.0,1,750.0,50,https://www.airbnb.com/rooms/53770992,15.000000,2021-12-13,2021-12
17630,211.0,1,6330.0,85,https://www.airbnb.com/rooms/53777865,74.470589,2021-12-13,2021-12
17631,195.0,1,5850.0,50,https://www.airbnb.com/rooms/53782321,117.000000,2021-12-13,2021-12
17632,85.0,6,2550.0,50,https://www.airbnb.com/rooms/53791212,51.000000,2021-12-13,2021-12

In [55]:
print(df.dtypes)

id                      int64
listing_url            object
scrape_id               int64
last_scraped           object
name                   object
                       ...
reviews_per_month     float64
sq_meters               int16
price_monthly         float32
price_sqm_amonth      float32
last_scraped_month     object
Length: 62, dtype: object

In [ ]:
# alright then i think im done with this first part we will come back to add postal codes to municipios AKA districts and msq2 rent prices x postal code.

-----

### Scrapping de web para recoger los codigos postales por Municipios de Mallorca

-------

#guardo el excel de la geo localizacion de los municipios

In [57]:
import pandas as pd
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By

In [59]:
opciones=Options()

opciones.add_experimental_option('excludeSwitches', ['enable-automation'])
opciones.add_experimental_option('useAutomationExtension', False)
opciones.headless=False    # si True, no aperece la ventana (headless=no visible)
opciones.add_argument('--start-maximized')         # comienza maximizado
#opciones.add_argument('user-data-dir=selenium')    # mantiene las cookies
#opciones.add_extension('driver_folder/adblock.crx')       # adblocker
opciones.add_argument('--incognito')

In [62]:
driver = ChromeDriverManager().install()#"./chromedriver.exe" #remember substitute this for your driver path
driver = webdriver.Chrome(driver,options = opciones)
url = 'https://www.uncodigopostal.nom.es/espana/1/codigos-postales-pueblos-Balears-Illes/7/1'
#other url : https://xn--cdigos-postales-vrb.cybo.com/espa%C3%B1a/islas-baleares/

/var/folders/94/v2x46p016qs_tyhzbgv7ywm40000gn/T/ipykernel_97335/3746678124.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(driver,options = opciones)

In [67]:
# im trying easy scrapping from a web - since seems quite a simple table
df_postales = pd.read_clipboard()
df_postales

                        Balears Illes  7730
  Alaior
  Alaro                 Balears Illes  7340
  Alcudia               Balears Illes  7400
  Algaida               Balears Illes  7210
  Andratx               Balears Illes  7150
  Ariany                Balears Illes  7529
...                               ...   ...
  Sineu                 Balears Illes  7510
  Soller                Balears Illes  7100
  Son Servera           Balears Illes  7550
  Valldemossa           Balears Illes  7170
  Vilafranca de Bonany  Balears Illes  7250

[66 rows x 2 columns]

In [68]:
df_postales.to_csv(r'../w4-ETL-Project/docs/scraped_postalcodes', index=False)

In [ ]:
d

In [64]:
driver.get(url)

test1= driver.find_elements(By.CLASS_NAME,'h3')

test1

[]